name: Deploy Blog

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: native
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install gems
        run: |
          bundle config set --local path 'vendor/bundle'
          bundle install

      - name: Build
        run: bundle exec jekyll build --destination /tmp/blog-${{ github.run_id }}

      - name: Deploy
        run: |
          rsync -a --delete /tmp/blog-${{ github.run_id }}/ /var/www/blog/
          rm -rf /tmp/blog-${{ github.run_id }}
